/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ExercisesRouteImport } from './routes/exercises'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionIdRouteImport } from './routes/session.$id'
import { Route as ProgramsIdRouteImport } from './routes/programs.$id'
import { Route as ApiParseSetRouteImport } from './routes/api/parse-set'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesRoute = ExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionIdRoute = SessionIdRouteImport.update({
  id: '/session/$id',
  path: '/session/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsIdRoute = ProgramsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProgramsRoute,
} as any)
const ApiParseSetRoute = ApiParseSetRouteImport.update({
  id: '/api/parse-set',
  path: '/api/parse-set',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/exercises': typeof ExercisesRoute
  '/history': typeof HistoryRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/parse-set': typeof ApiParseSetRoute
  '/programs/$id': typeof ProgramsIdRoute
  '/session/$id': typeof SessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/exercises': typeof ExercisesRoute
  '/history': typeof HistoryRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/parse-set': typeof ApiParseSetRoute
  '/programs/$id': typeof ProgramsIdRoute
  '/session/$id': typeof SessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/exercises': typeof ExercisesRoute
  '/history': typeof HistoryRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/parse-set': typeof ApiParseSetRoute
  '/programs/$id': typeof ProgramsIdRoute
  '/session/$id': typeof SessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent'
    | '/exercises'
    | '/history'
    | '/programs'
    | '/api/chat'
    | '/api/parse-set'
    | '/programs/$id'
    | '/session/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent'
    | '/exercises'
    | '/history'
    | '/programs'
    | '/api/chat'
    | '/api/parse-set'
    | '/programs/$id'
    | '/session/$id'
  id:
    | '__root__'
    | '/'
    | '/agent'
    | '/exercises'
    | '/history'
    | '/programs'
    | '/api/chat'
    | '/api/parse-set'
    | '/programs/$id'
    | '/session/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRoute: typeof AgentRoute
  ExercisesRoute: typeof ExercisesRoute
  HistoryRoute: typeof HistoryRoute
  ProgramsRoute: typeof ProgramsRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  ApiParseSetRoute: typeof ApiParseSetRoute
  SessionIdRoute: typeof SessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises': {
      id: '/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof ExercisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$id': {
      id: '/session/$id'
      path: '/session/$id'
      fullPath: '/session/$id'
      preLoaderRoute: typeof SessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$id': {
      id: '/programs/$id'
      path: '/$id'
      fullPath: '/programs/$id'
      preLoaderRoute: typeof ProgramsIdRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/api/parse-set': {
      id: '/api/parse-set'
      path: '/api/parse-set'
      fullPath: '/api/parse-set'
      preLoaderRoute: typeof ApiParseSetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProgramsRouteChildren {
  ProgramsIdRoute: typeof ProgramsIdRoute
}

const ProgramsRouteChildren: ProgramsRouteChildren = {
  ProgramsIdRoute: ProgramsIdRoute,
}

const ProgramsRouteWithChildren = ProgramsRoute._addFileChildren(
  ProgramsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRoute: AgentRoute,
  ExercisesRoute: ExercisesRoute,
  HistoryRoute: HistoryRoute,
  ProgramsRoute: ProgramsRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  ApiParseSetRoute: ApiParseSetRoute,
  SessionIdRoute: SessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
